Subir todos los cambios sobre test v8

diff --git a/.github/workflows/ci_cd_pipeline.yml b/.github/workflows/ci_cd_pipeline.yml
--- a/.github/workflows/ci_cd_pipeline.yml
+++ b/.github/workflows/ci_cd_pipeline.yml
@@ -79,12 +79,15 @@ jobs:
     needs: deploy
 
     steps:
+      - name: Obtener URL del servicio desplegado
+        run: echo "CLOUD_RUN_URL=${{ env.CLOUD_RUN_URL }}"
+
       - name: Ejecutar prueba de integración
         env:
           CLOUD_RUN_URL: ${{ env.CLOUD_RUN_URL }}
         run: |
           for i in {1..5}; do
-            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$CLOUD_RUN_URL/data" || echo "Error")
+            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$CLOUD_RUN_URL/data" || echo "000")
             if [ "$RESPONSE" -eq 200 ]; then
               echo "Prueba de integración pasada: La API devolvió HTTP 200"
               exit 0
@@ -149,9 +152,9 @@ jobs:
           python Flask-api/app.py &
           APP_PID=$!
           sleep 5
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080/data || echo "Error")
-          if [[ "$RESPONSE" == "Error" ]]; then
-            echo "Error: El servidor Flask no está respondiendo"
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080/data || echo "000")
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Error: El servidor Flask no está respondiendo correctamente"
             kill $APP_PID
             exit 1
           else
