Subir todos los cambios sobre test v9.3

diff --git a/.github/workflows/ci_cd_pipeline.yml b/.github/workflows/ci_cd_pipeline.yml
--- a/.github/workflows/ci_cd_pipeline.yml
+++ b/.github/workflows/ci_cd_pipeline.yml
@@ -123,6 +123,21 @@ jobs:
           fi
           echo "Prueba de integración pasada: El mensaje fue ingresado y se refleja en la API"
 
+      - name: Verificar tiempo de respuesta
+        env:
+          CLOUD_RUN_URL: ${{ env.CLOUD_RUN_URL }}
+        run: |
+          START=$(date +%s%N)
+          curl -s "$CLOUD_RUN_URL/data" > /dev/null
+          END=$(date +%s%N)
+          DURATION=$((($END - $START)/1000000))  # Convertir a milisegundos
+          echo "Tiempo de respuesta: $DURATION ms"
+          if [ $DURATION -gt 1000 ]; then
+            echo "Error: La API tardó más de 1000ms en responder"
+            exit 1
+          fi
+          echo "Tiempo de respuesta dentro del rango aceptable"
+
   unit_tests:
     name: Ejecutar prueba unitaria básica
     runs-on: ubuntu-latest
